# NOTE: the "adaptive" theme file gets created and updated by wezterm in response
# to system dark/light colour scheme changes
theme = "adaptive"

[editor]
auto-format = true
cursorline = false
mouse = false
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "error"

[keys.insert]
# Unreakable CTRL+S saving habit
C-s = [":write", "normal_mode"]

[keys.normal]
# Unreakable CTRL+S saving habit
C-s = ":write"
# vim habit
G = "goto_file_end"

# Yazi https://github.com/sxyazi/yazi/pull/2461
C-y = [
  ':sh rm -f /tmp/helix-yazi-ifc',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/helix-yazi-ifc',
  ':insert-output echo "\x1b[?1049h" > /dev/tty',
  ':open %sh{cat /tmp/helix-yazi-ifc}',
  ':redraw'
]
